export const PROGRESS_TIME = 'PROGRESS_TIME';
export const UPDATE_EVENT_STATUS = 'UPDATE_EVENT_STATUS';

export const PLACE_ROAD = 'PLACE_ROAD';
export const PLACE_BUILDING = 'PLACE_BUILDING';
export const INCREASE_BUILDING_TARGET_HEIGHT = 'INCREASE_BUILDING_TARGET_HEIGHT';
