export const PROGRESS_TIME = 'PROGRESS_TIME';
export const UPDATE_EVENT_STATUS = 'UPDATE_EVENT_STATUS';
export const RESET = 'RESET';


export const PLACE_STREET = 'PLACE_STREET';
export const PLACE_BUILDING = 'PLACE_BUILDING';
export const INCREASE_BUILDING_TARGET_HEIGHT = 'INCREASE_BUILDING_TARGET_HEIGHT';
export const EXTEND_STREETS = 'EXTEND_STREETS';
